import 'package:intl/intl.dart';

/// Jakim E-solat API model.
/// Generated by https://jsontodart.zariman.dev/
class JakimEsolatModel {
  List<PrayerTime>? prayerTime;
  String? status;
  String? serverTime;
  // String? periodType;
  // String? lang;
  String? zone;
  // String? bearing;

  JakimEsolatModel({
    this.prayerTime,
    this.status,
    this.serverTime,
    // this.periodType,
    // this.lang,
    this.zone,
    // this.bearing
  });

  JakimEsolatModel.fromJson(Map<String, dynamic> json) {
    prayerTime = json["prayerTime"] == null
        ? null
        : (json["prayerTime"] as List)
            .map((e) => PrayerTime.fromJson(e))
            .toList();
    status = json["status"];
    serverTime = json["serverTime"];
    // periodType = json["periodType"];
    // lang = json["lang"];
    zone = json["zone"];
    // bearing = json["bearing"];
  }
}

class PrayerTime {
  List<int>? times;

  PrayerTime({this.times});

  PrayerTime.fromJson(Map<String, dynamic> json) {
    String pattern = 'd-MMM-y HH:mm:ss';
    // hijri = json["hijri"];
    var date = json["date"];
    var imsak = json["imsak"];
    var fajr = json["fajr"];
    var syuruk = json["syuruk"];
    var dhuhr = json["dhuhr"];
    var asr = json["asr"];
    var maghrib = json["maghrib"];
    var isha = json["isha"];
    times = [
      DateFormat(pattern).parse('$date $imsak').millisecondsSinceEpoch,
      DateFormat(pattern).parse('$date $fajr').millisecondsSinceEpoch,
      DateFormat(pattern).parse('$date $syuruk').millisecondsSinceEpoch,
      DateFormat(pattern)
          .parse('$date $syuruk')
          .add(const Duration(minutes: 28))
          .millisecondsSinceEpoch,
      DateFormat(pattern).parse('$date $dhuhr').millisecondsSinceEpoch,
      DateFormat(pattern).parse('$date $asr').millisecondsSinceEpoch,
      DateFormat(pattern).parse('$date $maghrib').millisecondsSinceEpoch,
      DateFormat(pattern).parse('$date $isha').millisecondsSinceEpoch,
    ];
  }
}
