// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABU2oLGpbQOlaaQ-6joJDBevJ4iyfu-6k',
    appId: '1:1012545476549:web:798bf9dfbbeb130d5a9dac',
    messagingSenderId: '1012545476549',
    projectId: 'malaysia-waktu-solat',
    authDomain: 'malaysia-waktu-solat.firebaseapp.com',
    databaseURL: 'https://malaysia-waktu-solat.firebaseio.com',
    storageBucket: 'malaysia-waktu-solat.appspot.com',
    measurementId: 'G-6042FTLD08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC508-2dTQmgoh-FpGY0O9AU0Xb5wogtgw',
    appId: '1:1012545476549:android:631d6aab3ef111555a9dac',
    messagingSenderId: '1012545476549',
    projectId: 'malaysia-waktu-solat',
    databaseURL: 'https://malaysia-waktu-solat.firebaseio.com',
    storageBucket: 'malaysia-waktu-solat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtO_RCilt-GifewCMybUbHZO7EPTqqGR8',
    appId: '1:1012545476549:ios:4101a5c6a995c6f45a9dac',
    messagingSenderId: '1012545476549',
    projectId: 'malaysia-waktu-solat',
    databaseURL: 'https://malaysia-waktu-solat.firebaseio.com',
    storageBucket: 'malaysia-waktu-solat.appspot.com',
    androidClientId: '1012545476549-nmbjd650586u2iquu0q0h3rrguekc8kp.apps.googleusercontent.com',
    iosBundleId: 'live.iqfareez.waktusolatmalaysia',
  );

}