/// Flutter icons MyMptIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyMptIcons
///      fonts:
///       - asset: fonts/MyMptIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class MyMptIcons {
  MyMptIcons._();

  static const _kFontFam = 'MyMptIcons';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData tasbih_plain =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
