name: (Release) Build App Bundle and upload to Google Play

on:
  release:
    types: [published]

jobs:
  build_appbundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # File can be encoded to base64 on https://base64.guru/converter/encode/file
      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEY_PROP }}" | base64 --decode > android/key.properties

      - name: Decoding android/key.jks
        run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/key.jks

      - name: Build release appbundle
        if: ${{ !github.event.release.prerelease }}
        run: flutter build appbundle

      - name: Upload aab
        uses: actions/upload-artifact@v4
        if: ${{ !github.event.release.prerelease }}
        with:
          name: aab-release
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Adding markdown
        if: ${{ !github.event.release.prerelease }}
        run: |
          echo :white_check_mark: Build appbundle **todo: Publish to Google Play** >> $GITHUB_STEP_SUMMARY

  upload_google_play:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    needs: build_appbundle
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: aab-release

      - name: Upload file to the assets release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: live.iqfareez.waktusolatmalaysia
          releaseFiles: "*.aab"
          track: production
          status: draft

      - name: Adding markdown
        run: |
          echo ":rocket: Uploaded to Google Play" >> $GITHUB_STEP_SUMMARY
