name: Build all on release

on:
  push:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"

      # File can be encoded to base64 on https://base64.guru/converter/encode/file
      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEY_PROP }}" | base64 --decode > android/key.properties

      - name: Decoding android/key.jks
        run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/key.jks

      - name: Build release appbundle
        if: "!github.event.release.prerelease"
        run: flutter build appbundle

      - name: Upload aab
        uses: actions/upload-artifact@v3
        # The previous job will likely to fail because of https://github.com/flutter/flutter/issues/126971
        # But that is false poisitive so we ignore it
        if: |
          !github.event.release.prerelease && 
          failure()
        with:
          name: app-release
          path: build/app/outputs/bundle/release/*.aab

      - name: Adding markdown
        if: "!github.event.release.prerelease && failure()"
        run: |
          echo :white_check_mark: Build appbundle **todo: Publish to Google Play** >> $GITHUB_STEP_SUMMARY

      - name: Build release APK(s) per ABIs
        if: always()
        run: |
          flutter pub get
          flutter build apk --split-per-abi

      - name: Adding markdown
        run: |
          echo ":white_check_mark: Build split apk" >> $GITHUB_STEP_SUMMARY

      - name: Upload apks
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: apk-releases
          path: build/app/outputs/apk/release/*.apk

      - name: Adding markdown
        run: |
          echo ":blue_heart: Using **`flutter --version`**" >> $GITHUB_STEP_SUMMARY

  upload_assets:
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Test
        run: |
          echo "TEST HERE" >> $GITHUB_STEP_SUMMARY

  upload_google_play:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Adding markdown
        run: |
          echo "hiii" >> $GITHUB_STEP_SUMMARY
